""""""""""""""""""
" PLUGIN MANAGER "
""""""""""""""""""


set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'ajmwagar/vim-deus'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tmhedberg/SimpylFold'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'pseewald/anyfold'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'neoclide/coc.nvim', {'branch': 'release'}

call vundle#end()
filetype plugin indent on

" Other plugins I use that isn't supported by plugin manager
" 
" CmdlineComplete: Auto complete in vim command line
" URL: https://web.archive.org/web/20200811120254/https://www.vim.org/scripts/script.php?script_id=2222
"
" cscope mapping for vim
" URL: https://web.archive.org/web/20200811120513/http://cscope.sourceforge.net/cscope_vim_tutorial.html

" disabled plugins
set runtimepath-=~/.vim/bundle/SimpylFold
set runtimepath-=~/.vim/bundle/AnyFold
set runtimepath-=~/.vim/bundle/YouCompleteMe


"""""""""""""""""""""""""
" GENERAL CONFIGURATION "
"""""""""""""""""""""""""


" Set wildmenu
set wildmenu
" Can switch buffer without writing
set hidden

" line number
set nu
" Turn on syntax highlighting
syntax on
" If backspace doesn't work like it should be
set bs=2

" Transform tabs into spaces
set tabstop=4
set expandtab
set shiftwidth=4

" Use SPACE as leader key
let mapleader = " "

" remap Esc to ii as Esc is too far
inoremap ii <Esc>

" Prev/Next buffer
nnoremap <C-k> 20k
nnoremap <C-j> 20j

" Switching buffer by number
nnoremap <leader>l :ToggleBufExplorer<CR>

" Insert current date and time in normal mode
:nnoremap <leader>m "=strftime("%b-%d-%Y %H:%M")<CR>P

" remap tab movements
nnoremap <C-l> gt 
nnoremap <C-h> gT 

" split window settings
set splitright
set splitbelow

" open help in a horizontal split
:cabbrev h vert h

""""""""""""""""""""""""
" CSCOPE CONFIGURATION "
""""""""""""""""""""""""


" add cscope database file
cs add $CSCOPE_DB

" Use relative path for tags
set cscoperelative


""""""""""""""""""""""""""""""
" VIM TERMINAL CONFIGURATION "
""""""""""""""""""""""""""""""


" Alias for opening terminal in right vertical split
" without creating a new copy of the current window
command Term :vs|:term ++curwin

" keyboard shortcut for openig vertical terminal
noremap <leader>v :Term<CR>

" keyboard shortcut for openig horizontal terminal
noremap <leader>h :term<CR>

" keyboard shortcut for openiga terminal in tab
noremap <leader>t :tab term<CR>

" Change to normal mode
tnoremap <C-n> <C-w>N


"""""""""""""""""""""""""
" PLUGINS CONFIGURATION "
"""""""""""""""""""""""""


" AnyFold configurations 
" autocmd Filetype * AnyFoldActivate
" set foldlevel=0


" deus colorscheme setup
" NOTE: Does't work properly in gnome-terminal
" may be it doesn't support true color?
set t_Co=256
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark " Setting dark mode
colorscheme deus
let g:deus_termcolors=256

" ycm set up
let g:ycm_global_ycm_extra_conf = '$HOME/.vim/bundle/YouCompleteMe/.ycm_extra_conf.py'
let g:ycm_min_num_of_chars_for_completion = 1
let g:ycm_collect_identifiers_from_comments_and_strings = 1
let g:ycm_filetype_whitelist = {'*': 1}
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_semantic_triggers = {'c': ['->', '.'], 'cpp': ['->', '.', '::']}
let g:ycm_collect_identifiers_from_tags_files = 1

" coc setup
let g:coc_node_path = '$HOME/bin/nodejs/bin/node'
source $HOME/dotfiles/vim/coc.vim

" NERDTree configuration
" Toggle NERDTree with Ctrl+n
map <C-n> :NERDTreeToggle<CR>

" SimplyFold configurations
let g:SimpylFold_docstring_preview=1

" tagbar configuration
map <F8> :TagbarToggle<CR>
